FROM node:latest

WORKDIR /usr/app
COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .

RUN npm install

COPY server.js .
COPY app .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start-server"]